### ISSUE TITLE
Fireworks don't respect protection

### ISSUE THREAD

**Issue by dontfwiththestream** [runsy/fireworkz#4]
Steps to reproduce: 

place firework in protected area
use second player to ignite firework

**Comment by runsy** [comment]
What is the problem? Fireworkz don't destroy anything.

**Comment by dontfwiththestream** [comment]
If i have some placed on my property to set off later, someone else can fire them. In my opinion they shouldn't be fire-able inside a protected space unless you are the owner of the area

**Comment by runsy** [comment]
ok fixed

**Comment by dontfwiththestream** [comment]
Hey thanks for the quick response on both of these issues, and good job on the mod!
